'use client';
import {useEffect,useRef,useState} from 'react';
import {channelFor,authorizationFor,parseCapture,validateItem,seal,open,merge,readLocal,saveLocal,type PocketItem,type Pending} from '../lib/pocket';
type State={items:PocketItem[];pending:Pending[];cursor:number};const empty:State={items:[],pending:[],cursor:0};
function Orb(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current!;const ctx=canvas.getContext('2d')!;let frame=0,raf=0;const draw=()=>{ctx.clearRect(0,0,240,180);for(let i=0;i<800;i++){const u=i*2.39996323;const y=1-2*(i+.5)/800;const r=Math.sqrt(1-y*y);const phase=frame*.004;const x=r*Math.cos(u+phase),z=r*Math.sin(u+phase);const wave=1+.07*Math.sin(u*4+phase*6+y*5);const scale=46*wave;ctx.fillStyle=`rgba(137,226,213,${.12+.68*(z+1)/2})`;ctx.beginPath();ctx.arc(120+x*scale,90+y*scale,.55+.6*(z+1)/2,0,Math.PI*2);ctx.fill();}frame++;raf=requestAnimationFrame(draw);};draw();return()=>cancelAnimationFrame(raf);},[]);return <canvas ref={ref} width={240} height={180} aria-label="Chef particle presence"/>;}
export default function Pocket(){
 const [tab,setTab]=useState<'capture'|'todo'|'thought'>('capture');const [token,setToken]=useState('');const [pair,setPair]=useState('');const [showPair,setShowPair]=useState(false);const [draft,setDraft]=useState('');const [kind,setKind]=useState<'todo'|'thought'>('todo');const [status,setStatus]=useState('Connect your Mac to begin');const [ready,setReady]=useState(false);const [state,setState]=useState<State>(empty);const [busy,setBusy]=useState(false);const input=useRef<HTMLTextAreaElement>(null);const syncBusy=useRef(false);const live=useRef(state);const connection=useRef('');const commits=useRef(Promise.resolve());const [loaded,setLoaded]=useState(false);
 useEffect(()=>{live.current=state;},[state]);
 useEffect(()=>{const hash=new URLSearchParams(location.hash.slice(1));const code=hash.get('pair');if(code){setPair(code);setShowPair(true);history.replaceState(null,'',location.pathname);}readLocal<string>('connection').then(v=>{if(v&&/^[a-f0-9]{64}$/.test(v))setToken(v);setReady(true);}).catch(e=>{setStatus(e.message);setReady(true);});if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
 useEffect(()=>{connection.current=token;setLoaded(false);if(!token)return;let cancelled=false;channelFor(token).then(async ch=>{const v=await readLocal<State>('channel:'+ch);if(!cancelled){live.current=v??empty;setState(v??empty);setLoaded(true);setStatus('Connected · checking for updates');await sync(token);}}).catch(e=>setStatus(e.message));return()=>{cancelled=true;};},[token]);
 async function commit(update:(value:State)=>State,currentToken=token){const operation=commits.current.catch(()=>{}).then(async()=>{if(connection.current!==currentToken)throw Error('Connection changed; try again.');const ch=await channelFor(currentToken);const next=update(live.current);await saveLocal('channel:'+ch,next);if(connection.current===currentToken){live.current=next;setState(next);}});commits.current=operation;await operation;}
 async function sync(currentToken=token){if(!currentToken||syncBusy.current)return;syncBusy.current=true;try{const ch=await channelFor(currentToken),bearer=await authorizationFor(currentToken);const path='/api/channels/'+ch+'/events';
 for(const event of [...live.current.pending]){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+bearer},body:JSON.stringify(event),signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('Sync paused. Captures are safely queued on this phone.');await commit(current=>({...current,pending:current.pending.filter(e=>e.id!==event.id)}),currentToken);}
 const after=live.current.cursor;const response=await fetch(path+'?after='+after,{headers:{Authorization:'Bearer '+bearer},cache:'no-store',signal:AbortSignal.timeout(20000)});if(response.status===401&&live.current.items.length===0){setStatus('Paired · add your first capture to start syncing');return;}if(!response.ok)throw Error('Sync unavailable. Your captures stay queued.');const body=await response.json() as {events:{seq:number,payload:string}[],cursor:number};if(!Array.isArray(body.events)||body.events.length>200)throw Error('Invalid sync response');const incoming:PocketItem[]=[];let cursor=after;for(const event of body.events){if(!Number.isSafeInteger(event.seq)||event.seq<=cursor)throw Error('Invalid sync cursor');const value=await open(currentToken,event.payload);if(!validateItem(value.item))throw Error('Invalid item');incoming.push(value.item);cursor=event.seq;}if(body.cursor!==cursor)throw Error('Invalid sync cursor');await commit(current=>({...current,items:incoming.reduce((items,item)=>merge(items,item),current.items),cursor}),currentToken);if(connection.current===currentToken)setStatus(live.current.pending.length?'Changes queued':'Saved to sync service · Mac updates when online');
 }catch(e){if(connection.current===currentToken)setStatus(e instanceof Error?e.message:'Sync unavailable; capture kept here');}finally{syncBusy.current=false;}}
 useEffect(()=>{if(!token)return;const timer=setInterval(()=>{void sync(token);},15000);const online=()=>{void sync(token);};window.addEventListener('online',online);return()=>{clearInterval(timer);window.removeEventListener('online',online);};},[token]);
 async function capture(){if(!token){setShowPair(true);return;}if(!loaded)return;setBusy(true);try{const parsed=parseCapture(draft,kind);const now=new Date().toISOString();const item:PocketItem={id:crypto.randomUUID(),...parsed,done:false,createdAt:now,updatedAt:now};const event={id:crypto.randomUUID(),payload:await seal(token,{v:1,op:'upsert',item})};await commit(current=>({...current,items:merge(current.items,item),pending:[...current.pending,event]}));setDraft('');setStatus('Saved on this phone · syncing');void sync();}catch(e){setStatus(e instanceof Error?e.message:'Could not save; your text is kept');}finally{setBusy(false);}}
 async function toggle(item:PocketItem){try{const changed={...item,done:!item.done,updatedAt:new Date().toISOString()};const event={id:crypto.randomUUID(),payload:await seal(token,{v:1,op:'upsert',item:changed})};await commit(current=>({...current,items:merge(current.items,changed),pending:[...current.pending,event]}));void sync();}catch{setStatus('Could not save that change. Please try again.');}}
 async function connect(){if(!/^[a-f0-9]{64}$/.test(pair.trim())){setStatus('Paste the pairing code from Chef → Phone.');return;}if(syncBusy.current){setStatus('Wait for the current sync to finish.');return;}if(live.current.pending.length){setStatus('Sync your pending captures before changing connections.');return;}try{await saveLocal('connection',pair.trim());setToken(pair.trim());setPair('');setShowPair(false);}catch{setStatus('Could not save pairing. Please try again.');}}
 const visible=state.items.filter(v=>v.kind===tab);const pending=state.pending.length;
 return <main><header><div className="wordmark">CHEF<span>POCKET</span></div><button className="connection" onClick={()=>setShowPair(true)}><i className={token?'dot':'dot muted'}/>{token?'Mac paired':'Connect Mac'}</button></header><section className="content"><div className="section-line"><span>{tab==='capture'?'A SMALL SPACE FOR YOUR DAY':tab==='todo'?'YOUR TO-DO LIST':'YOUR THOUGHTS'}</span><button className="text-button" onClick={()=>void sync()} disabled={!token}>↻ Sync</button></div>
 {tab==='capture'?<><Orb/><h1>What’s on your mind?</h1><p className="intro">A task to do. A thought to keep.<br/>Your Chef, wherever you are.</p><div className="capture-card"><div className="kind-switch"><button className={kind==='todo'?'selected':''} onClick={()=>setKind('todo')}>✓ To-do</button><button className={kind==='thought'?'selected':''} onClick={()=>setKind('thought')}>✧ Thought</button></div><textarea ref={input} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={650} placeholder={kind==='todo'?'Hey Chef, add grab groceries to my to-do list':'Hey Chef, add get Sy a Snorlax for Christmas to my thoughts'} aria-label="Capture a task or thought"/><div className="capture-actions"><button className="text-button" onClick={()=>{input.current?.focus();setStatus('Use the microphone on your Android keyboard to dictate.');}}>Use keyboard mic</button><button className="save" onClick={()=>void capture()} disabled={busy||!ready||(!!token&&!loaded)||!draft.trim()}>{busy?'Saving…':'Save ↗'}</button></div></div><div className="recent"><h2>RECENT CAPTURES</h2>{state.items.slice(0,3).map(item=><article key={item.id}><span className="item-symbol">{item.kind==='todo'?'✓':'✧'}</span><div><p>{item.text}</p><small>{item.kind==='todo'?'To-do':'Thought'} · {new Date(item.createdAt).toLocaleDateString()}</small></div></article>)}{!state.items.length&&<p className="empty">Your first capture will appear here.</p>}</div></>:<><h1>{tab==='todo'?'Make room for what matters.':'Keep the little things.'}</h1><p className="intro">{visible.length} {tab==='todo'?'tasks':'thoughts'} · saved with Chef</p><div className="list">{visible.map(item=><article key={item.id}>{tab==='todo'?<button className={'check '+(item.done?'done':'')} onClick={()=>void toggle(item)} aria-label={item.done?'Mark incomplete':'Mark complete'}>{item.done?'✓':''}</button>:<span className='item-symbol'>✧</span>}<div><p className={item.done?'crossed':''}>{item.text}</p><small>{new Date(item.createdAt).toLocaleDateString()}</small></div></article>)}{!visible.length&&<p className="empty">Nothing here yet. Add one from Capture.</p>}</div><button className="save wide" onClick={()=>{setKind(tab==='todo'?'todo':'thought');setTab('capture');}}>+ Add {tab==='todo'?'a task':'a thought'}</button></>}
 <p role="status" className="sync-status">{status}{pending>0&&<span> · {pending} pending</span>}</p><p className="privacy">The Mac processes synced items while Chef is running. No phone control.</p></section><nav aria-label="Main navigation"><button className={tab==='capture'?'active':''} onClick={()=>setTab('capture')}><b>◉</b>Capture</button><button className={tab==='todo'?'active':''} onClick={()=>setTab('todo')}><b>✓</b>To-dos</button><button className={tab==='thought'?'active':''} onClick={()=>setTab('thought')}><b>✧</b>Thoughts</button></nav>
 {showPair&&<div className="modal-backdrop"><section className="pair-modal" role="dialog" aria-modal="true" aria-label="Connect your Mac"><button className="close" onClick={()=>setShowPair(false)} aria-label="Close">×</button><h2>Your Chef. Both devices.</h2><p>On your Mac, open Chef → Controls → Phone. Choose Connect phone, then open the pairing link here or paste its code.</p><label>Pairing code<input value={pair} onChange={e=>setPair(e.target.value)} placeholder="Paste your Mac’s pairing code" autoComplete="off" type="password"/></label><button className="save wide" onClick={()=>void connect()}>Pair with my Mac</button><p className="privacy">Only to-dos and thoughts are synced. Content is encrypted before it leaves either device. Keep the pairing link private.</p><p className="privacy">In Chrome’s menu, choose Add to Home screen to keep Chef on your phone. For voice capture, use your keyboard’s mic; this app doesn’t listen in the background.</p>{token&&<button className="text-button" onClick={async()=>{if(live.current.pending.length){setStatus('Sync pending captures before disconnecting.');return;}await saveLocal('connection','');setToken('');setState(empty);live.current=empty;setShowPair(false);setStatus('Mac disconnected');}}>Disconnect this phone</button>}</section></div>}
 </main>;
}
