package com.danieljansen.chefpocket;

import android.Manifest;
import android.content.ContentValues;
import android.database.Cursor;
import android.provider.CalendarContract;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.pm.PackageManager;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.RectF;
import android.graphics.Typeface;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.ScrollView;
import android.widget.TextView;
import java.util.List;

public final class MainActivity extends Activity {
    private static final int AUDIO=44,NOTIFICATIONS=45;
    private final Handler handler=new Handler(Looper.getMainLooper());
    private final Runnable poll=()->{RelaySync.request(this);refresh();handler.postDelayed(thisPoll(),20_000);};
    private String tab="capture",status="Connect your Mac to sync to-dos and thoughts.";
    private String calendarDraftToClarify;
    private LinearLayout root,content,nav;
    private PocketStore store;
    private boolean receiverRegistered;
    private PhoneVoice phoneVoice;
    private final BroadcastReceiver messages=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){if(RelaySync.ACTION_STATUS.equals(i.getAction()))status=i.getStringExtra(RelaySync.EXTRA_STATUS);else if(WakeCaptureService.ACTION_STATE.equals(i.getAction()))status=i.getStringExtra(WakeCaptureService.EXTRA_STATE);refresh();}};
    private Runnable thisPoll(){return poll;}

    @Override protected void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(0xff071419);getWindow().setNavigationBarColor(0xff071419);getWindow().getDecorView().setSystemUiVisibility(0);store=new PocketStore(this);build();}
    @Override protected void onResume(){super.onResume();IntentFilter f=new IntentFilter();f.addAction(RelaySync.ACTION_STATUS);f.addAction(WakeCaptureService.ACTION_STATE);androidx.core.content.ContextCompat.registerReceiver(this,messages,f,androidx.core.content.ContextCompat.RECEIVER_NOT_EXPORTED);receiverRegistered=true;RelaySync.request(this);handler.removeCallbacks(poll);handler.postDelayed(poll,20_000);refresh();}
    @Override protected void onPause(){handler.removeCallbacks(poll);if(receiverRegistered){unregisterReceiver(messages);receiverRegistered=false;}super.onPause();}

    @Override protected void onDestroy(){if(phoneVoice!=null)phoneVoice.close();super.onDestroy();}

    private void build(){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xff071419);root.setPadding(dp(22),dp(8),dp(22),0);root.setOnApplyWindowInsetsListener((view,insets)->{int left,top,right,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=insets.getInsets(android.view.WindowInsets.Type.systemBars()|android.view.WindowInsets.Type.displayCutout());left=bars.left;top=bars.top;right=bars.right;bottom=bars.bottom;}else{left=insets.getSystemWindowInsetLeft();top=insets.getSystemWindowInsetTop();right=insets.getSystemWindowInsetRight();bottom=insets.getSystemWindowInsetBottom();}view.setPadding(dp(22)+left,dp(8)+top,dp(22)+right,bottom);return insets;});setContentView(root);
        LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);TextView brand=label("CHEF",20,0xffe9f5f3,true);TextView pocket=label("  POCKET",12,0xff77c9be,true);LinearLayout word=new LinearLayout(this);word.setGravity(Gravity.CENTER_VERTICAL);word.addView(brand);word.addView(pocket);header.addView(word,new LinearLayout.LayoutParams(0,dp(58),1));Button connect=quietButton("Connect Mac");connect.setOnClickListener(v->pairDialog());header.addView(connect);root.addView(header);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(0,dp(12),0,dp(24));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setPadding(0,dp(9),0,dp(13));root.addView(nav);
        render();
    }
    private void render(){if(content==null)return;content.removeAllViews();nav.removeAllViews();
        TextView eyebrow=label(tab.equals("capture")?"A SMALL SPACE FOR YOUR DAY":tab.equals("todo")?"YOUR TO-DO LIST":tab.equals("calendar")?"CALENDAR REQUESTS":"YOUR THOUGHTS",11,0xff86a4a5,true);eyebrow.setLetterSpacing(.14f);content.addView(eyebrow,spaced(0,0,0,8));
        if(tab.equals("capture")){
            OrbView orb=new OrbView(this);LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-1,dp(154));op.bottomMargin=dp(8);content.addView(orb,op);
            TextView title=label("What’s on your mind?",27,0xffe9f5f3,true);title.setGravity(Gravity.CENTER);content.addView(title);
            TextView intro=label("A task to do. A thought to keep.\nYour Chef, wherever you are.",15,0xff93a9a8,false);intro.setGravity(Gravity.CENTER);intro.setLineSpacing(dp(3),1);content.addView(intro,spaced(0,8,0,18));
            panel();TextView prompt=label("Speak or type a capture",13,0xffa8bfbd,true);content.addView(prompt);
            Button typed=primaryButton("＋  Type a to-do, thought, or date");typed.setOnClickListener(v->captureDialog("todo"));content.addView(typed,spaced(0,13,0,8));
            if(isListening()){Button talk=quietButton("Talk now · capture the next sentence");talk.setOnClickListener(v->{try{startService(new Intent(this,WakeCaptureService.class).setAction(WakeCaptureService.ACTION_TALK_NOW));}catch(Exception e){status="Could not start Talk capture. Use typed capture instead.";refresh();}});content.addView(talk,spaced(0,0,0,8));}
            Button speaker=quietButton("Test Chef voice");speaker.setOnClickListener(v->{if(phoneVoice==null)phoneVoice=new PhoneVoice(this,message->{status=message;refresh();});status="Playing Chef voice · use your phone's Media volume";phoneVoice.speak("Hello. I'm Chef. My voice is ready.");});content.addView(speaker,spaced(0,0,0,8));
            LinearLayout voice=new LinearLayout(this);voice.setGravity(Gravity.CENTER_VERTICAL);CheckBox handsfree=new CheckBox(this);handsfree.setButtonTintList(android.content.res.ColorStateList.valueOf(0xff78d7cb));handsfree.setTextColor(0xffe9f5f3);handsfree.setText(R.string.handsfree_label);handsfree.setChecked(isListening());handsfree.setOnClickListener(v->{if(handsfree.isChecked())requestHandsfree();else stopHandsfree();});voice.addView(handsfree,new LinearLayout.LayoutParams(0,-2,1));TextView mic=label(isListening()?"● LIVE":"OFF",10,isListening()?0xff7fe0d3:0xff809897,true);voice.addView(mic);content.addView(voice,spaced(0,2,0,3));
            TextView disclosure=label("When enabled, Chef listens offline while the persistent notification is shown. Only a capture after “hey chef” is saved. Audio is not stored or uploaded. Talk now is an explicit one sentence capture. Handsfree stops after 12 hours. Confirmations use your Fish Audio Chef voice, available offline. Use Media volume to adjust it.",12,0xff8da3a1,false);disclosure.setLineSpacing(dp(3),1);content.addView(disclosure,spaced(0,4,0,0));unpanel();
            TextView recent=label("RECENT CAPTURES",11,0xff86a4a5,true);recent.setLetterSpacing(.13f);content.addView(recent,spaced(0,24,0,8));List<PocketStore.Item> items=safeItems(null);int count=Math.min(3,items.size());for(int i=0;i<count;i++)addItem(items.get(i),false);if(count==0)content.addView(label("Your first capture will appear here.",14,0xff809897,false));
        }else{
            TextView title=label(tab.equals("todo")?"Make room for what matters.":tab.equals("calendar")?"Put it on your calendar.":"Keep the little things.",26,0xffe9f5f3,true);content.addView(title,spaced(0,15,0,7));List<PocketStore.Item> items=safeItems(tab);String countLabel=tab.equals("todo")?" to-dos":tab.equals("calendar")?" calendar requests":" thoughts";content.addView(label(items.size()+countLabel+" · saved with Chef",14,0xff93a9a8,false),spaced(0,0,0,18));
            panel();if(items.isEmpty())content.addView(label("Nothing here yet. Add one from Capture.",14,0xff809897,false));for(PocketStore.Item item:items)addItem(item,tab.equals("todo"));unpanel();if(tab.equals("calendar")){Button choose=primaryButton("Choose a calendar on this phone");choose.setOnClickListener(v->ensureCalendarAccess());content.addView(choose,spaced(0,16,0,5));}Button add=quietButton(tab.equals("todo")?"＋  Add a to-do":tab.equals("calendar")?"＋  Add a calendar request":"＋  Add a thought");add.setOnClickListener(v->captureDialog(tab));content.addView(add,spaced(0,8,0,0));
        }
        TextView sync=label(status+(store.pendingCount()>0?" · "+store.pendingCount()+" queued":""),12,0xff7fa6a2,false);sync.setLineSpacing(dp(2),1);content.addView(sync,spaced(0,20,0,3));TextView privacy=label("To-dos, thoughts, and calendar requests sync encrypted with your paired Mac. Saved text never starts desktop actions.",11,0xff66807e,false);privacy.setLineSpacing(dp(2),1);content.addView(privacy);
        for(String name:new String[]{"capture","todo","thought","calendar"}){String caption=name.equals("todo")?"To-dos":name.equals("thought")?"Thoughts":name.equals("calendar")?"Calendar":"Capture";Button b=quietButton((tab.equals(name)?"●  ":"○  ")+caption);b.setTextColor(tab.equals(name)?0xff8de0d5:0xff8aa09f);b.setOnClickListener(v->{tab=name;render();});nav.addView(b,new LinearLayout.LayoutParams(0,dp(48),1));}
    }
    private void refresh(){runOnUiThread(this::render);}
    private List<PocketStore.Item> safeItems(String kind){try{return store.items(kind);}catch(Exception e){status="Device storage error. Your previous captures are still on this phone.";return java.util.Collections.emptyList();}}
    private void addItem(PocketStore.Item item,boolean withToggle){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.TOP|Gravity.CENTER_VERTICAL);row.setPadding(dp(11),dp(11),dp(11),dp(11));row.setBackground(roundRect(0xff102328,13));LinearLayout.LayoutParams rp=spaced(0,0,0,7);content.addView(row,rp);
        if(withToggle&&item.kind.equals("todo")){CheckBox check=new CheckBox(this);check.setChecked(item.done);check.setButtonTintList(android.content.res.ColorStateList.valueOf(item.done?0xff76d7ca:0xff77918f));check.setOnClickListener(v->{try{store.save(new PocketStore.Item(item.id,item.kind,item.text,check.isChecked(),item.createdAt,java.time.Instant.now().toString()),PocketStore.readToken(this));RelaySync.request(this);refresh();}catch(Exception e){status="Could not update this to-do. Try again.";refresh();}});row.addView(check);}
        else{TextView symbol=label(item.kind.equals("todo")?"✓":"✧",18,0xff80d8ce,true);symbol.setGravity(Gravity.CENTER);row.addView(symbol,new LinearLayout.LayoutParams(dp(32),dp(32)));}
        LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.setPadding(dp(9),0,0,0);TextView text=label(item.text,14,item.done?0xff80918f:0xffe0ecea,false);if(item.done)text.setPaintFlags(text.getPaintFlags()|Paint.STRIKE_THRU_TEXT_FLAG);words.addView(text);String detail=item.kind.equals("todo")?"TO-DO":item.kind.equals("thought")?"THOUGHT":item.done?"ADDED ON PHONE":"CALENDAR REQUEST";words.addView(label(detail+" · "+item.createdAt.substring(0,10),10,0xff839a98,true),spaced(0,5,0,0));row.addView(words,new LinearLayout.LayoutParams(0,-2,1));
    }
    private void captureDialog(String defaultKind){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(22),dp(8),dp(22),0);TextView hint=label(defaultKind.equals("calendar")?"Use a clear date, such as tomorrow. Calendar access is optional.":"Save locally now. It will sync when Chef is paired and online.",13,0xff94aaa8,false);box.addView(hint);String[] kinds={"To-do","Thought","Calendar"};String[] values={"todo","thought","calendar"};int initial=defaultKind.equals("thought")?1:defaultKind.equals("calendar")?2:0;final String[] selected={values[initial]};RadioGroup group=new RadioGroup(this);group.setOrientation(RadioGroup.HORIZONTAL);for(int i=0;i<kinds.length;i++){RadioButton option=new RadioButton(this);option.setText(kinds[i]);option.setTextColor(0xffdbe8e6);option.setButtonTintList(android.content.res.ColorStateList.valueOf(0xff78d7cb));option.setTag(values[i]);option.setId(2100+i);group.addView(option,new RadioGroup.LayoutParams(0,-2,1));if(i==initial)option.setChecked(true);}group.setOnCheckedChangeListener((g,id)->{View checked=g.findViewById(id);if(checked!=null)selected[0]=(String)checked.getTag();});box.addView(group,spaced(0,6,0,0));EditText field=new EditText(this);field.setTextColor(0xffedf5f3);field.setHintTextColor(0xff6c8583);field.setHint(defaultKind.equals("thought")?"A thought to keep":defaultKind.equals("calendar")?"Dentist tomorrow at 3 PM":"A task to remember");if(defaultKind.equals("calendar")&&calendarDraftToClarify!=null){field.setText(calendarDraftToClarify);field.setSelection(field.length());calendarDraftToClarify=null;}field.setMinLines(2);field.setMaxLines(5);field.setGravity(Gravity.TOP);field.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES|InputType.TYPE_TEXT_FLAG_MULTI_LINE);box.addView(field,spaced(0,8,0,4));new AlertDialog.Builder(this).setTitle("Capture with Chef").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{if(selected[0].equals("calendar")){calendarCapture(field.getText().toString());return;}try{CaptureParser.Capture capture=CaptureParser.parse(field.getText().toString(),selected[0]);String now=java.time.Instant.now().toString();store.save(new PocketStore.Item(java.util.UUID.randomUUID().toString(),capture.kind,capture.text,false,now,now),PocketStore.readToken(this));status="Saved on this phone · syncing";RelaySync.request(this);render();}catch(Exception e){status=e.getMessage()==null?"Could not save this capture.":e.getMessage();render();}}).show();}
    private void pairDialog(){EditText code=new EditText(this);code.setSingleLine(true);code.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);code.setHint("Paste the 64 character pairing code");code.setTextColor(0xffeaf4f2);code.setHintTextColor(0xff79918f);new AlertDialog.Builder(this).setTitle("Connect your Mac").setMessage("On your Mac, open Chef → Controls → Phone → Show pairing. Paste its pairing code here. Treat the code like a password.").setView(code).setNegativeButton("Cancel",null).setPositiveButton("Pair",(d,w)->connectToken(code.getText().toString().trim())).setNeutralButton("Disconnect",(d,w)->{PocketStore.clearToken(this);status="Mac disconnected. Local captures stay on this phone.";refresh();}).show();}
    private void connectToken(String token){if(!PocketCrypto.validToken(token)){status="Paste the 64 character pairing code from Chef on Mac.";refresh();return;}try{String nextChannel=PocketCrypto.channel(token);String current=PocketStore.readToken(this);if(current!=null&&!current.equals(token)){status="This phone is already paired. Disconnect first before switching the pairing code.";refresh();return;}String previous=getSharedPreferences("chef-pocket-channel",0).getString("channel","");if(!previous.isEmpty()&&!previous.equals(nextChannel)){if(store.pendingCount()>0){status="Sync the previous pairing's queued captures before changing Macs.";refresh();return;}new AlertDialog.Builder(this).setTitle("Switch this phone to another Mac?").setMessage("Switching removes the cached items from the previous Mac from this phone. It does not delete them on that Mac. Save any local captures you still need before switching.").setNegativeButton("Keep current data",null).setPositiveButton("Clear this phone and switch",(d,w)->{try{store.clearLocalForNewChannel();completePair(token,nextChannel);}catch(Exception e){status="Could not clear the previous local cache.";refresh();}}).show();return;}completePair(token,nextChannel);}catch(Exception e){status="Could not securely save this pairing code.";refresh();}}
    private void completePair(String token,String channel){try{boolean alreadyPaired=channel.equals(getSharedPreferences("chef-pocket-channel",0).getString("channel", ""));PocketStore.saveToken(this,token);getSharedPreferences("chef-pocket-channel",0).edit().putString("channel",channel).apply();if(!alreadyPaired)store.enqueueAll(token);status="Paired · syncing your captures";RelaySync.request(this);render();}catch(Exception e){status="Could not securely save this pairing code.";refresh();}}
    private boolean isListening(){return WakeCaptureService.isRunning();}
    private void requestHandsfree(){
        new AlertDialog.Builder(this).setTitle("Enable handsfree capture?").setMessage("Chef Pocket will keep the microphone active while the screen is locked. Offline recognition stays on this phone. Only text spoken after “hey chef” is saved; audio is not recorded or uploaded. A persistent notification shows when listening, and you can stop it there at any time.").setNegativeButton("Cancel",(d,w)->refresh()).setPositiveButton("Continue",(d,w)->requestAudioPermission()).show();
    }
    private void requestAudioPermission(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED){startHandsfree();return;}requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},AUDIO);}
    private void startHandsfree(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},NOTIFICATIONS);return;}Intent i=new Intent(this,WakeCaptureService.class).setAction(WakeCaptureService.ACTION_START);try{startForegroundService(i);}catch(Exception e){status="Android could not start the microphone service. Open Chef Pocket and try again.";refresh();}}
    private void stopHandsfree(){stopService(new Intent(this,WakeCaptureService.class));status="Voice capture stopped";refresh();}
    @Override public void onRequestPermissionsResult(int requestCode,String[] permissions,int[] grants){super.onRequestPermissionsResult(requestCode,permissions,grants);if(requestCode==AUDIO){if(grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)startHandsfree();else{status="Microphone permission is needed for handsfree. Typed capture still works.";refresh();}}else if(requestCode==NOTIFICATIONS){if(grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)startHandsfree();else{status="Allow notifications to show the listening control, then enable handsfree.";refresh();}}else if(requestCode==CALENDAR_PERMISSIONS){if(grants.length>=2&&grants[0]==PackageManager.PERMISSION_GRANTED&&grants[1]==PackageManager.PERMISSION_GRANTED)chooseCalendar();else{status="Calendar access was declined. Your calendar request is saved on this phone.";refresh();}}}
    private void panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(16),dp(16),dp(16),dp(16));p.setBackground(roundRect(0xff0d1e23,19));content.addView(p,spaced(0,0,0,0));content=(LinearLayout)p;}
    private void unpanel(){LinearLayout p=content;content=(LinearLayout)p.getParent();}
    private LinearLayout.LayoutParams spaced(int left,int top,int right,int bottom){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(dp(left),dp(top),dp(right),dp(bottom));return lp;}
    private int dp(float value){return (int)(value*getResources().getDisplayMetrics().density+.5f);}
    private TextView label(String text,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(text);v.setTextSize(size);v.setTextColor(color);if(bold)v.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    private Button quietButton(String text){Button b=new Button(this);b.setText(text);b.setTextSize(12);b.setAllCaps(false);b.setMinHeight(dp(40));b.setTextColor(0xffb3c6c4);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(0xff102328));return b;}
    private Button primaryButton(String text){Button b=new Button(this);b.setText(text);b.setTextSize(14);b.setAllCaps(false);b.setTextColor(0xff071b1c);b.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));b.setMinHeight(dp(48));b.setBackground(roundRect(0xff82d9cf,14));return b;}
    private android.graphics.drawable.GradientDrawable roundRect(int color,int radius){android.graphics.drawable.GradientDrawable d=new android.graphics.drawable.GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private static final int CALENDAR_PERMISSIONS=46;
    private void calendarCapture(String phrase){
        try {
            CalendarParser.Result result=CalendarParser.parseTyped(phrase,java.time.ZoneId.systemDefault());
            JSONObjectRequest request=new JSONObjectRequest(result.startAt,result.endAt,result.allDay,result.timeZone);
            String now=java.time.Instant.now().toString();PocketStore.Item item=new PocketStore.Item(java.util.UUID.randomUUID().toString(),"calendar",result.title,false,now,now,request.json());
            store.save(item,PocketStore.readToken(this));calendarDraftToClarify=null;status="Calendar request saved · choose a calendar to add it";RelaySync.request(this);refresh();
            ensureCalendarAccess();
        }catch(Exception e){calendarDraftToClarify=phrase;status=e.getMessage()==null?"Say a clear event and date, for example ‘Dentist tomorrow’.":e.getMessage();captureDialog("calendar");refresh();}
    }
    private static final class JSONObjectRequest {final String start,end,zone;final boolean allDay;JSONObjectRequest(String s,String e,boolean a,String z){start=s;end=e;allDay=a;zone=z;}org.json.JSONObject json()throws Exception{org.json.JSONObject o=new org.json.JSONObject();o.put("startAt",start);o.put("endAt",end);o.put("allDay",allDay);o.put("timeZone",zone);return o;}}
    private void ensureCalendarAccess(){if(checkSelfPermission(Manifest.permission.READ_CALENDAR)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.WRITE_CALENDAR)==PackageManager.PERMISSION_GRANTED){chooseCalendar();return;}requestPermissions(new String[]{Manifest.permission.READ_CALENDAR,Manifest.permission.WRITE_CALENDAR},CALENDAR_PERMISSIONS);}
    private void chooseCalendar(){try{Cursor c=getContentResolver().query(CalendarContract.Calendars.CONTENT_URI,new String[]{CalendarContract.Calendars._ID,CalendarContract.Calendars.CALENDAR_DISPLAY_NAME,CalendarContract.Calendars.ACCOUNT_NAME,CalendarContract.Calendars.CALENDAR_ACCESS_LEVEL},CalendarContract.Calendars.VISIBLE+"=1",null,null);if(c==null)throw new IllegalStateException();java.util.ArrayList<Long> ids=new java.util.ArrayList<>();java.util.ArrayList<String> names=new java.util.ArrayList<>();while(c.moveToNext()){int access=c.getInt(3);if(access>=CalendarContract.Calendars.CAL_ACCESS_CONTRIBUTOR){ids.add(c.getLong(0));names.add(c.getString(1)+" · "+c.getString(2));}}c.close();if(ids.isEmpty()){status="No writable calendar found. The request is saved here until you choose one.";refresh();return;}new AlertDialog.Builder(this).setTitle("Choose where to add calendar captures").setMessage("Chef will add explicit calendar captures to the calendar you select. This only creates events on this phone; it does not control the Mac.").setItems(names.toArray(new String[0]),(d,which)->{getSharedPreferences("calendar-choice",0).edit().putLong("calendar",ids.get(which)).apply();flushCalendarRequests(ids.get(which));}).setNegativeButton("Cancel",(d,w)->{status="Calendar request saved · choose a calendar to add it";refresh();}).show();}catch(SecurityException e){status="Calendar access is off. Your calendar request stays saved on this phone.";refresh();}catch(Exception e){status="Could not read calendars. Your request stays saved on this phone.";refresh();}}
    private void flushCalendarRequests(long calendarId){try{for(PocketStore.Item item:store.items("calendar")){if(item.done)continue;try{CalendarExecutor.add(this,store,calendarId,item);PocketStore.Item added=new PocketStore.Item(item.id,item.kind,item.text,true,item.createdAt,java.time.Instant.now().toString(),item.calendarRequest);store.save(added,PocketStore.readToken(this));status="Calendar event added on this phone";}catch(Exception e){status="Calendar request saved · Android could not add it yet";}}RelaySync.request(this);}catch(Exception e){status="Calendar request saved · choose a writable calendar to add it";}refresh();}
    private void exportPendingCalendar(){for(PocketStore.Item item:safeItems("calendar"))if(!item.done)status="Calendar request saved · choose a calendar to add it";}
    private static final class OrbView extends View{private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);private final long started=System.currentTimeMillis();OrbView(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}@Override protected void onDraw(Canvas canvas){super.onDraw(canvas);float cx=getWidth()/2f,cy=getHeight()/2f;float radius=Math.min(getWidth()*.29f,getHeight()*.48f);float phase=(System.currentTimeMillis()-started)*.00025f;for(int i=0;i<420;i++){double angle=i*2.39996323;double y=1-2*(i+.5)/420;double r=Math.sqrt(1-y*y);double z=r*Math.sin(angle+phase);float x=(float)(r*Math.cos(angle+phase));float py=(float)y;float glow=(float)((z+1)/2);paint.setColor(0xff62cbbb);paint.setAlpha((int)(35+175*glow));canvas.drawCircle(cx+x*radius,cy+py*radius,(float)(.65+1.35*glow),paint);}postInvalidateDelayed(50);}}
}
